<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.10.7" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Web/jable.html" />
    <EmbeddedResource Include="Web/jable.css" />
    <EmbeddedResource Include="Web/jable.mjs" />
  </ItemGroup>
</Project>
